model_list:
  - model_name: "my-gemini"
    litellm_params:
      model: "vertex_ai/gemini-2.5-flash"
      vertex_project: "project-6f2f73ef-798c-4cfb-a32"
      vertex_location: "europe-west3"
      vertex_credentials: "google-credentials.json"

general_settings:
  master_key: "sk-1234"
  drop_params: true