model_list:
  - model_name: my-gemini
    litellm_params:
      model: vertex_ai/gemini-3.5-flash
      vertex_project: project-28eb8bc8-d6d7-4a2d-aaf
      vertex_location: global
      vertex_credentials: /app/google-credentials.json
      reasoning_effort: low

  - model_name: my-gemini-fallback
    litellm_params:
      model: vertex_ai/gemini-2.5-flash
      vertex_project: project-28eb8bc8-d6d7-4a2d-aaf
      vertex_location: global
      vertex_credentials: /app/google-credentials.json
      reasoning_effort: low

general_settings:
  master_key: sk-1234
  database_url: os.environ/DATABASE_URL

router_settings:
  routing_strategy: simple-shuffle

  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT

  num_retries: 3
  timeout: 60
  cooldown_time: 60
  allowed_fails: 1
  max_fallbacks: 2

  fallbacks:
    - {"my-gemini": ["my-gemini-fallback"]}

  default_fallbacks:
    - my-gemini-fallback

litellm_settings:
  cache: true
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT